//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KudrDiplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        private static Entities _context;
        public Entities()
            : base("name=Entities")
        {
        }
        public static Entities GetContext()
        {
            if (_context == null)
                _context = new Entities();
            return _context;
        }
        public static Entities CreateNewContext()
        {
            return new Entities();
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Итоговые_Работы> Итоговые_Работы { get; set; }
        public virtual DbSet<Курсы> Курсы { get; set; }
        public virtual DbSet<Курсы_Учащихся> Курсы_Учащихся { get; set; }
        public virtual DbSet<Пользователи_Курсы> Пользователи_Курсы { get; set; }
        public virtual DbSet<Посещения> Посещения { get; set; }
        public virtual DbSet<Расписание> Расписание { get; set; }
        public virtual DbSet<Регистрация> Регистрация { get; set; }
        public virtual DbSet<Учащиеся> Учащиеся { get; set; }
    }
}
