//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KudrDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Курсы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Курсы()
        {
            this.Итоговые_Работы = new HashSet<Итоговые_Работы>();
            this.Курсы_Учащихся = new HashSet<Курсы_Учащихся>();
            this.Пользователи_Курсы = new HashSet<Пользователи_Курсы>();
            this.Посещения = new HashSet<Посещения>();
            this.Расписание = new HashSet<Расписание>();
        }
    
        public int ID_Курса { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Итоговые_Работы> Итоговые_Работы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Курсы_Учащихся> Курсы_Учащихся { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пользователи_Курсы> Пользователи_Курсы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Посещения> Посещения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание> Расписание { get; set; }
    }
}
