//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KudrDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещения
    {
        public int ID_Посещения { get; set; }
        public int ID_Учащегося { get; set; }
        public int ID_Курса { get; set; }
        public Nullable<System.DateTime> Дата_посещения { get; set; }
        public string Статус { get; set; }
    
        public virtual Курсы Курсы { get; set; }
        public virtual Учащиеся Учащиеся { get; set; }
    }
}
